### ISSUE TITLE
New Collections Not Appearing on Dashboard/Home Page

### ISSUE THREAD

**Issue by lightonphiri** [slumou/simpledl#3]
I have successfully added two new collections by running **import.pl -> index.pl -> generate --all** , however, these collections do not appear on the dashboard when accessing index.html ([simpledl DIR]/public_html/index.html

That being said, I am able to access the new collections by changing the URLs to point to the newly created collections, e.g. via **[simpledl DIR]/public_html/metadata/[COLLECTION]/index.html**

**Comment by slumou** [comment]
Try "generate --website --force".
The index.html page is generated on the basis of the index.xml but the index.xml has not changed, while the collection listing has.  This is one of the few places where more advanced dependency management may help but I am not convinced it is yet worth the effort.

**Comment by lightonphiri** [comment]
./generate.pl --website --force did the trick! Thank you.

I am wondering why ./generate --all did not work: one would expect the parameter to also do what "--website --force" does.

**Comment by slumou** [comment]
--all generates all pages using the normal "conditional compilation" dependency checks
--force generates pages by ignoring dependency checks and rebuilding everything anyway
